---
# Install dependencies
- name: Install required packages
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: true

# Ensure MySQL service is running
- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: true

# Use unix_socket authentication for root initially
- name: Set MySQL root password using unix_socket
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    state: present

# Ensure root uses mysql_native_password (switch auth plugin)
- name: Ensure root user uses mysql_native_password
  community.mysql.mysql_user:
    name: root
    host: localhost
    plugin: mysql_native_password
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    state: present


# Create application database
- name: Create application database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Create application MySQL user
- name: Create application MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL,GRANT"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Import schema into database
- name: Import Petclinic schema into database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: import
    target: /tmp/petclinic_schema.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: petclinic_import_schema | default(true)
