- name: Ensure files dir exists
  file:
    path: "{{ role_path }}/files"
    state: directory
    mode: '0755'

- name: Copy WAR to Tomcat webapps
  copy:
    src: files/spring-petclinic.jar
    dest: /opt/spring-petclinic/spring-petclinic.jar
    owner: root
    group: root
    mode: '0644'
  notify: Restart Tomcat

handlers:
  - name: Start Spring Boot app
    shell: |
      # Stop existing app if running
      pkill -f spring-petclinic || true
      # Start app in background
      nohup java -jar /opt/spring-petclinic/spring-petclinic.jar > /opt/spring-petclinic/app.log 2>&1 &
    args:
      executable: /bin/bash
