---
- name: Ensure app directory exists
  file:
    path: /opt/spring-petclinic
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: Copy Spring Petclinic JAR to server
  copy:
    src: files/spring-petclinic.jar
    dest: /opt/spring-petclinic/spring-petclinic.jar
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  notify: Start Spring Boot app
