---
- name: Install Java 17
  become: yes
  apt:
    name: openjdk-17-jre
    state: present
    update_cache: yes

- name: Ensure app directory exists
  file:
    path: /opt/spring-petclinic
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: Generate application.properties dynamically
  template:
    src: application.properties.j2
    dest: /opt/spring-petclinic/application.properties
    owner: ubuntu
    group: ubuntu
    mode: '0644'


- name: Copy Spring Petclinic JAR to server
  copy:
    src: files/spring-petclinic.jar
    dest: /opt/spring-petclinic/spring-petclinic.jar
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- import_tasks: systemd.yml
