---
- name: Start Spring Boot app
  shell: |
    pkill -f spring-petclinic || true
    nohup java -jar /opt/spring-petclinic/spring-petclinic.jar > /opt/spring-petclinic/app.log 2>&1 &
    sleep 5
    pgrep -f spring-petclinic
  args:
    executable: /bin/bash
