---
- name: Start Spring Boot app
  shell: |
    echo "🔍 Checking if JAR exists..."
    if [ ! -f /opt/spring-petclinic/spring-petclinic.jar ]; then
      echo "❌ JAR not found at /opt/spring-petclinic/spring-petclinic.jar"
      exit 1
    fi

    echo "🧠 Checking Java..."
    if ! command -v java >/dev/null 2>&1; then
      echo "❌ Java not found in PATH"
      exit 1
    fi

    echo "🛑 Stopping any existing process..."
    pkill -f spring-petclinic || true

    echo "🚀 Starting Spring Boot app..."
    nohup java -jar /opt/spring-petclinic/spring-petclinic.jar > /opt/spring-petclinic/app.log 2>&1 &

    echo "🕐 Waiting for startup..."
    sleep 10

    echo "📋 Checking process..."
    if ! pgrep -f spring-petclinic; then
      echo "❌ App not running! Showing last 20 lines of log:"
      tail -n 20 /opt/spring-petclinic/app.log || true
      exit 1
    else
      echo "✅ App started successfully!"
    fi
  args:
    executable: /bin/bash
