---
- name: Start Spring Boot app
  shell: |
    echo "🔍 Checking if JAR exists..."
    if [ ! -f /opt/spring-petclinic/spring-petclinic.jar ]; then
      echo "❌ JAR not found at /opt/spring-petclinic/spring-petclinic.jar"
      exit 1
    fi

    echo "🧠 Checking Java..."
    java -version || echo "⚠️ Java check failed (will continue)"

    echo "🛑 Stopping any existing process..."
    pkill -f spring-petclinic || true

    echo "🚀 Starting Spring Boot app in background..."
    nohup java -jar /opt/spring-petclinic/spring-petclinic.jar > /opt/spring-petclinic/app.log 2>&1 &
    sleep 10

    echo "📋 Checking process..."
    if pgrep -f spring-petclinic; then
      echo "✅ App started successfully!"
    else
      echo "❌ App not running! Showing last 20 lines of log:"
      tail -n 20 /opt/spring-petclinic/app.log || true
    fi
  args:
    executable: /bin/bash
