on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_DIR: terraform


jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Backend
        run: |
          chmod +x ./create-backend.sh
          ./create-backend.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan -lock=false -var="key_name=${{ secrets.AWS_KEY_NAME }}"

      - name: Export Terraform Output
        working-directory: ./terraform
        run: terraform output -json > tfoutput.json

      - name: Upload tfoutput.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfoutput
          path: tfoutput.json
